### ISSUE TITLE
Stage{1}@BUG: Provide Null support for Gson

### ISSUE THREAD

**Issue by ahinchman1** [ahinchman1/TornadoFX-Suite#20]

**Comment by ahinchman1** [comment]
Gson does not serialize Nulls without you specifying that in the creation of the Gson object. Gson does provide support for such, as can be seen in documentation here:

https://sites.google.com/site/gson/gson-user-guide#TOC-Null-Object-Support

However, this is not what I want.  Turning on the serialization for Null only restores null elements in the Node objects themselves.  What I need is to implement support in KParser to simply interpret primitive null assignments in Kotlin variables here:

```
    private fun getValue(value: JsonObject): String {
        val gValue = value.get("value")
        return when (value.get("form").asJsonPrimitive.toString()) {
            "\"BOOLEAN\"" ->  gValue.asBoolean.toString()
            "\"FLOAT\"" -> gValue.asFloat.toString()
            "\"INT\"" -> gValue.asInt.toString()
            "\"CHAR\"" -> gValue.asCharacter.toString()
            "\"NULL\"" -> gValue.asJsonNull.toString() <-- HERE
            else -> "Unrecognized value type"
        }
    }
```

to prevent this error:

```
java.lang.IllegalStateException: Not a JSON Null: "null"
	at com.google.gson.JsonElement.getAsJsonNull(JsonElement.java:140)
	at com.github.ast.parser.KParser.getValue(KParser.kt:247)
```

**Comment by ahinchman1** [comment]
Wow I'm dumb jk I just replaced that with "null"
