### ISSUE TITLE
Stage{1}@BUG: Provide more flexible function access levels (public/private/protected)

### ISSUE THREAD

**Issue by ahinchman1** [ahinchman1/TornadoFX-Suite#9]
java.lang.ClassCastException: kastree.ast.Node$Modifier$AnnotationSet cannot be cast to kastree.ast.Node$Modifier$Lit
	at com.github.hd.tornadofxsuite.controller.ClassScanner.captureFunction(ClassScanner.kt:69)
	at com.github.hd.tornadofxsuite.controller.ClassScanner.parseAST(ClassScanner.kt:34)
	at com.github.hd.tornadofxsuite.controller.FXTestGenerator.readFiles(FXTestGenerator.kt:48)
	at com.github.hd.tornadofxsuite.controller.FXTestGenerator.fileOutputRead(FXTestGenerator.kt:37)
	at com.github.hd.tornadofxsuite.controller.FXTestGenerator.access$fileOutputRead(FXTestGenerator.kt:15)

**Comment by ahinchman1** [comment]
Bug solved, but will need to edit the current data objects `BareBreakDown`, `ClassProperties` to be able to detect access levels. 

This is the current detection levels: 
<img width="700" alt="screen shot 2018-09-23 at 4 37 33 pm" src="https://user-images.githubusercontent.com/6917498/45933486-60ade500-bf53-11e8-8966-28b3e09fe780.png">
